// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwdxcabvqhhyvqkgcshf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3ZHhjYWJ2cWhoeXZxa2djc2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzEyMTYsImV4cCI6MjA2NTU0NzIxNn0.LEjhwRhGAEeAOhCDzXun_6N7mt8lp9TbyhYW8M7AD_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);